<?php
     $og_image = 'https://mjmacfadden.github.io/cryptoswatches/img/featured-img/esthetic-monte-featured-img.png'; // Set before including header
    include '../header.php'; // Include header
?>
<div class="swatch-hero py-5" style="background-color:#52B7E1;">
    <div class="container my-4 shadow-img">
        <div class="d-flex justify-content-center align-items-center mb-4">
            <img src="img/000425.png" class="img-fluid" alt="">
        </div>
        <a href="swatch/esthetic_monte.php#swatch-description">
            <i class="bi bi-chevron-double-down"></i>
        </a>
    </div>
</div>

<div class="container my-4 shadow-img">
    <div class="row mt-4 pb-5" id="swatch-description">
        <h1>ESthetic Monte</h1>
        <h4>by Michael Macfadden</h4>
        <p><strong>Please introduce yourself to our readers:</strong></p>
        <p>Hello, my name is Peter, the creator of the Esthetic Monte Collection on the WAX blockchain. I&rsquo;m a graphics designer located in California, USA. I&rsquo;ve navigated myself through the creative corporate world where I am currently a Creative Director for a marketing agency. I&rsquo;m particularly interested in this social experiment of the NFT community.</p>
        <p><strong>What was the inspiration for this piece?</strong></p>
        <p>This piece was based on the proposed drop date, May the fourth, I wanted to create a War of the Stars type of key art; the Tyche Collection visuals are generated by a neural network. For this piece I was listening to the Jam Pearl, this piece is the visualization of a lyric &ldquo;I know someday you&rsquo;ll have a beautiful life, I know you&rsquo;ll be a star, In somebody else&rsquo;s sky, but why can&rsquo;t it be mine?&rdquo;</p>
        <p><strong>How long have you been creating in the digital realm?</strong></p>
        <p>The &ldquo;digital realm&rdquo;, what exactly does that mean&hellip;lol. I&rsquo;ve been mastering graphic design for the past 18 years typically working to deliver assets for the digital realm. As for creating and publishing on the blockchain, I started this year. With the genesis project minting in February.</p>
        <p><strong>Can you tell us about your workflow (what equipment and software do you use to create)?</strong></p>
        <p>I recently discovered the artificial intelligence power of a neural network and its capability of creating a visual based on a phrase I input. What&rsquo;s interesting about this process is like the human brain, ideas come from phrases, words, stories, movies, and experiences; those ideas can manifest into imagination which then leads to inspiration. It&rsquo;s a very difficult process to tap into, however, the A.I. is able to create a unique visual from the words in a matter of minutes. Amazing.</p>
        <p>If I was to take the same phrase, I would ponder over it for who knows how long, most likely overthink it, try to find some abstract way to go about it; quite frankly over complicate it. I then take this asset into photoshop for post-production. I lean on my graphic design experience to create collectible art in the form of a card.</p>
        <p><strong>Who are your artistic influences?</strong></p>
        <p>There are so many, but to name a few; Jean-Michel Basquiat, Barbara Kruger, Andy Warhol, Stefan Sagmeister, David Carson, Dr. Seuss, @toonpaintNFT, @ShnazzyNFTs, the WAX fam&hellip;</p>
        <p><strong>What got you interested in NFTs/Crypto Art/Digital Collectibles?</strong></p>
        <p>Like so many others, I was drawn into the NFT space with the launch of the TopShot NFT collection. I couldn&rsquo;t tell you what blockchain, or what marketplace that collection was launched on, but the visuals they created drew me in. It wasn&rsquo;t about the tech or the cryptocurrency at all for me. Initially, I was drawn to the foil packs they created. It triggered the nostalgic cord in my brain, from there I started researching NFT creation.</p>
        <p>For me, it&rsquo;s about trying to reverse engineer the experience to arrive at a project. I found myself watching YouTube videos on the subject. One day the algorithm feed me a NiftyBC tutorial on how to mint NFTs on the WAX blockchain. From my little research and headlines about &ldquo;Gas Fees&rdquo; the cost of entry on the ETH blockchain was crazy. But what Nifty was pushing was attainable, had the ability to create packs, and away I went&hellip;I consider myself a Time-traveling Mutant. I learned about the WAX blockchain and how to mint assets on the NeftyBlocks platform from @MORBS15 🙏 . Shortly after creating my Twitter account as part of the verification process with something like 5 followers @FromNullToZero somehow found me and offered to promote my work, that 🚀 the collection. I can&rsquo;t thank those two people enough.</p>
        <p><strong>Where can we find you online?</strong></p>
        <ul>
        <li>You can find the Esthetic Monte website at:&nbsp;<a dir="ltr" title="https://estheticmonte.com" href="https://estheticmonte.com/" target="_blank" rel="noopener noreferrer">https://estheticmonte.com</a></li>
        <li>Twitter:&nbsp;<a dir="ltr" title="https://twitter.com/Esthetic_Monte" href="https://twitter.com/Esthetic_Monte" target="_blank" rel="noopener">https://twitter.com/Esthetic_Monte</a></li>
        <li>Nefty Blocks:&nbsp;<a dir="ltr" title="https://neftyblocks.com/c/estheticmnte" href="https://neftyblocks.com/c/estheticmnte" target="_blank" rel="noopener noreferrer">https://neftyblocks.com/c/estheticmnte</a></li>
        <li>Atomichub:&nbsp;<a dir="ltr" title="https://wax.atomichub.io/creator/collection/estheticmnte" href="https://wax.atomichub.io/creator/collection/estheticmnte" target="_blank" rel="noopener noreferrer">https://wax.atomichub.io/creator/collection/estheticmnte</a></li>
        </ul>
        <p><strong>Anything else you&rsquo;d like to share?</strong></p>
        <p>I like to thank CryptoSwatches for the opportunity to collaborate and showcase my artwork on their platform. I&rsquo;m honored to be canonized alongside the many talented artists on the collab roster.</p>
    </div>
</div>

<div class="swatch-footer py-5" style="background-color:#A8DBF0;">
    <div class="container my-4 shadow-img">
        <div class="row mt-4">
            <div class="col d-flex justify-content-center align-items-center mb-4">
                <img src="img/000423.png" class="img-fluid lightbox" alt="ESthetic_Monte">
            </div>
            <div class="col d-flex justify-content-center align-items-center mb-4">
                <img src="img/000424.png" class="img-fluid lightbox" alt="ESthetic_Monte">
            </div>
            <div class="col d-flex justify-content-center align-items-center mb-4">
                <img src="img/000425.png" class="img-fluid lightbox" alt="ESthetic_Monte">
            </div>
            <div class="col d-flex justify-content-center align-items-center mb-4">
                <img src="img/000426.gIF" class="img-fluid lightbox" alt="ESthetic_Monte">
            </div>

        </div>
        <div class="row">
            <div class="col-6">
                <a href="swatch/kaosmoon_circle.php"><i class="bi bi-arrow-left"></i> KAOSMOON_CIRCLE</a>
            </div>
            <div class="col-6 text-end">
                <a href="swatch/maiki-nft-2.php">MAIKI_NFT <i class="bi bi-arrow-right"></i></a>
            </div>
        </div>
    </div>
</div>


<?php
    include '../footer.php'; // Include footer
?>
